<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('home'); ?>">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('members'); ?>">Members</a> <span class="divider">/</span></li>
    <li class="active"><a href="<?php echo $this->url('members/userpage', array('username'=>'adamlundrigan')); ?>">Adam Lundrigan</a></li>
</ul>

<div class="row">
<div class="span1" style="text-align:center">
    <?php echo $this->gravatar('adam@lundrigan.ca'); ?><br />
    <a href="http://github.com/adamlundrigan" target="_blank">GitHub</a><br />
    <a href="http://twitter.com/adamlundrigan" target="_blank">Twitter</a><br />
    <a href="http://adam.lundrigan.ca" target="_blank">Blog</a><br />
</div>
<div class="span10">
    <h1>Adam Lundrigan</h1>
    <p>Senior Progammer at CDLI (www.cdli.ca). Co-founder of @NLWebDevs. Purveyor of PHP5. Small-time OSS contributor. Enjoys squashing Zend Framework bugs (almost) too much.  Will push Zend Framework 2 on anyone who will listen, and even those who won't.  Worst CounterStrike/BF3/CoD player EVAR.</p>
</div>
</div>
