<?php echo $this->doctype(); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Newfoundland & Labrador Web Developers Group')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->appendStylesheet($this->basePath() . '/css/style.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->appendFile($this->basePath() . '/js/jquery-1.7.2.min.js')
                                  ->appendFile($this->basePath() . '/js/bootstrap.min.js') ?>

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-32514569-1']);
      _gaq.push(['_setDomainName', 'nlwebdevs.com']);
      _gaq.push(['_setDomainName', 'nlwebdevs.ca']);
      _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">NLWebDevs</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
              <li><a href="<?php echo $this->url('members') ?>">Members</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <div style="float:right">Version <?php $SHA=$this->escapeHtml(file_get_contents('data/version')); ?><a href="https://github.com/nlwebdevs/website/tree/<?php echo $SHA; ?>" target="_blank"><?php echo $SHA; ?></a></div>
        <p>&copy; <?php echo date('Y'); ?> Newfoundland &amp; Labrador Web Developers Group.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
