  <div class="well">
    <h3>Welcome to the...</h3>
    <h1>Newfoundland &amp; Labrador Web Developers Group</h1>
    <h4 style="padding: 10px 0 0 20px">
        <a href="http://www.facebook.com/groups/363546917037669" target="_blank">Facebook</a> &nbsp;&middot;&nbsp;
        <a href="http://twitter.com/nlwebdevs" target="_blank">Twitter</a> &nbsp;&middot;&nbsp;
        <a href="https://www.google.com/a/cpanel/nlwebdevs.ca" target="_blank">Google Apps</a> &nbsp;&middot;&nbsp;
        <a href="https://github.com/nlwebdevs" target="_blank">GitHub</a>
    </h4>
  </div>
  <div class="row">
    <div class="span4">
      <h2>About Us</h2>
      <p>We are <a href="/members">bunch</a> of web developers based in <a href="http://en.wikipedia.org/wiki/Newfoundland_and_Labrador" target="_blank">Newfoundland &amp; Labrador</a> who all have something in common: a love of programming.  Sound like you?  Then what are you waiting for, join us!</p>
      <p><a class="btn btn-success" href="#" target="_blank">Find out more! &raquo;</a></p>
   </div>
   <div class="span4">
      <h2>Upcoming Events</h2>
      <i>Nothing to see here yet...</i>
  </div>
  <div class="span4">
      <h2>Meeting History</h2>
      <ul>
          <li><a href="https://docs.google.com/a/nlwebdevs.ca/document/d/1YKZqzIZtq8KONNq1pTvHKkpVEjj-ZwU4o6vfDaUQtUI/edit" target="_blank">Meeting Minutes: 2012/06/06</a></li>
          <li><a href="https://docs.google.com/a/nlwebdevs.ca/document/d/1_XY2Q_SOQIVguBxjsxmHLdtA49AOqn3RBaggnGfJU_M/edit" target="_blank">Meeting Minutes: 2012/05/24</a></li>
      </ul>
   </div>
  </div>
