  <div class="well">
    <h3>Welcome to the...</h3>
    <h1>Newfoundland &amp; Labrador Web Developers Group</h1>
    <h4 style="padding: 10px 0 0 20px">
        <a href="http://www.facebook.com/groups/363546917037669" target="_blank">Facebook</a> &nbsp;&middot;&nbsp;
        <a href="http://twitter.com/nlwebdevs" target="_blank">Twitter</a> &nbsp;&middot;&nbsp;
        <a href="https://www.google.com/a/cpanel/nlwebdevs.ca" target="_blank">Google Apps</a> &nbsp;&middot;&nbsp;
        <a href="https://github.com/nlwebdevs" target="_blank">GitHub</a>
    </h4>
  </div>
  <div class="row">
    <div class="span4">
      <h2>First Box</h2>
      <p>First box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first box first.</p>
      <p><a class="btn btn-success" href="#" target="_blank">A Button! &raquo;</a></p>
   </div>
   <div class="span4">
      <h2>Second Box</h2>
      <p>Second box second box second box second box second box second box second box second box second box second box second box second box second box second box second box second box second box second box second box second box.</p>
      <p><a class="btn btn-success" href="#" target="_blank">A Button! &raquo;</a></p>
  </div>
  <div class="span4">
      <h2>Third Box</h2>
      <p>Third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box third box.</p>
      <p><a class="btn btn-success" href="#" target="_blank">A Button! &raquo;</a></p>
   </div>
  </div>
